### ISSUE TITLE
Travis build failing due to old version of golang

### ISSUE THREAD

**Issue by frextrite** [coala/coala-bears#2843]
Travis build for [coala/coala-bears/#2836](https://github.com/coala/coala-bears/pull/2836) is failing with the following error:
```
# golang.org/x/tools/go/internal/gcimporter
../../../gopath/src/golang.org/x/tools/go/internal/gcimporter/bexport.go:212: obj.IsAlias undefined (type *types.TypeName has no field or method IsAlias)
# golang.org/x/tools/go/internal/packagesdriver
../../../gopath/src/golang.org/x/tools/go/internal/packagesdriver/sizes.go:94: undefined: types.SizesFor
The command ".ci/deps.go.sh" failed and exited with 2 during .
```

This problem persists if an old verion of Go language is used according to this [issue](https://github.com/golang/lint/issues/421) which states that Go <= 1.8 is no longer supported.

Currently Travis CI testing is done on trusty, so either the latest version of golang needs to be manually installed in trusty images or an updated version of ubuntu needs to be used for testing. 

Further input from maintainers is required to come at a conclusion.

`area/ci`
`type/bug`

**Comment by jayvdb** [comment]
Thanks for opening this @frextrite - initiative.

I raised an upstream issue in gometalinter, and they closed it saying go 1.9 was minimum supported, while we are using go 1.5 in CI.

The easiest fix is to bypass the exit code , and disable some more linters in CI as they no longer work in our CI, and hope the others work on go 1.5.

Another approach is to tell gometalinter to install all except the two broken ones.

A bit harder is installing go 1.9.

**Comment by utkarsh2102** [comment]
@jayvdb, I think we should consider enabling the linters that we want.
That should fix the problem for now.
And meanwhile, we can think of upgrading to 1.9.
Thoughts?

**Comment by jayvdb** [comment]
Note earlier issue https://github.com/coala/coala-bears/issues/2829 about similar problems.  This is going to keep happening with go until we fix the underlying problem of the CI worker having a very old version of go.

Nominally assigned to @frextrite , but ill step in and fix all the breakages at the end of the weekend if there are not high quality fixes already ready by then.

**Comment by frextrite** [comment]
@jayvdb Actually what I'm doing doesn't involve upgrading golang. We'll still be using go v1.7.4 and it'll work. I'm upgrading the gometalinter package to the latest version and install the dependencies using the newer method and this fixes the problem.(The old method was using `gometalinter --install` which is now deprecated)

Initially, I thought of upgrading golang to the latest version, but then the above fix worked and I stopped looking further. Though our priority should be using the latest stable version of golang so that further problems don't arise.
